package com.rag.openai.domain.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;

/**
 * Represents a choice in an OpenAI chat completion response.
 * 
 * @param index The index of this choice
 * @param message The message generated by the model
 * @param finishReason The reason the model stopped generating tokens
 */
public record Choice(
    int index,
    Message message,
    @JsonProperty("finish_reason") String finishReason
) {
    public Choice {
        Objects.requireNonNull(message, "Message must not be null");
        if (index < 0) {
            throw new IllegalArgumentException("Index must be non-negative");
        }
    }
}
